_wandb:
    value:
        cli_version: 0.22.1
        e:
            ipatw26k8o3lzch57pbcr698yjw3f7nm:
                codePath: scripts/train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "46111125504"
                        used: "30574997504"
                email: olavo.dalberto@acad.ufsm.br
                executable: /mnt/dados/gpt_ed_assistant/.venv/bin/python
                git:
                    commit: 4bcfbd97e3617ddb48af620ed7451372c9c426a9
                    remote: https://github.com/olavodd42/gpt_ed_assistant.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-95838dcd-7007-0b30-33c0-f762e0e9f09f
                host: olavo-dalberto-Dell-G15-5515
                memory:
                    total: "16080216064"
                os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
                program: /mnt/dados/gpt_ed_assistant/scripts/train.py
                python: CPython 3.11.9
                root: /mnt/dados/gpt_ed_assistant/scripts
                startedAt: "2025-09-30T20:39:47.957901Z"
                writerId: ipatw26k8o3lzch57pbcr698yjw3f7nm
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
            "4": 3.11.9
            "5": 0.22.1
            "6": 4.55.4
            "12": 0.22.1
            "13": linux-x86_64
